# Test your FastAPI endpoints
###
GET http://{{base_url}}/topics
X-Api-key: {{api_key}}
Accept: application/json

###
GET http://127.0.0.1:8000/departments
X-Api-key: {{api_key}}
Accept: application/json

###
GET http://127.0.0.1:8000/statuses
X-Api-key: {{api_key}}
Accept: application/json

###
GET http://127.0.0.1:8000/tickets/?email=efr-communications-prod@cuf.pt&status_id=10&limit=10&offset=0
X-Api-key: {{api_key}}
Accept: application/json

###
GET http://127.0.0.1:8000/tickets/?status_id=3&dept_id=22&topic_id=22&EFR=Médis,SAMS Norte
X-Api-key: {{api_key}}
Accept: application/json

###
GET http://127.0.0.1:8000/tickets/?status_id=23&topic_id=47&dept_id=53,22
X-Api-key: {{api_key}}
Accept: application/json